### PR TITLE
fix(client_test): Improve flakyness of shape lifecycle test 

### PR DESCRIPTION
**Pull request by davidmartos96**
It looks like the new test `notifies for shape lifecycle` can fail with the postgres driver. When expecting 1 notifications, 2 were sent instead. This seems to be because the subscription data is emitted before the `Process.subscribe` ends (there is an `await setMeta` that can take a bit longer than the 1 ms delay the mock uses, when using the Postgres driver. 

I don't know if there is better way to solve this.

cc @msfstef

### CODE REVIEW

**Review by msfstef — COMMENTED** [review]
I'm happy with the `notifies for shape lifecycle` test to also sync the shape fully and _then_ assert that there are 2 notifications and check them individually (essentially making sure the order is correct) to avoid timing issues altogether, since there's always a chance that the order messes up because of unpredictable IO.

**Comment by davidmartos96** [comment]
@msfstef That can work too, good point. I've updated it

**Review by msfstef — APPROVED** [review]

**Comment by msfstef** [comment]
Thanks for the fix! Should've foreseen that there would be timing issues :)

**Comment by davidmartos96** [comment]
> Thanks for the fix! Should've foreseen that there would be timing issues :)

No problem! A bit of a hidden issue though, since the CI doesn't run the node postgres driver. Our SQLite tests also suffice with the 1 ms delay.

**Pull request merged**
