### PR TITLE
fix: make sure to deduplicate subscribe calls on the client

### PR DESCRIPTION
**Pull request by icehaunter**

### CODE REVIEW

**Review by alco — COMMENTED** [review]
Beautiful :heart:

**Review by thruflo — APPROVED** [review]
All looks great 👍 

I note no tests. Presumably the existing tests exercise the code but might be nice to verify the intended dedupe behaviour.

**Comment by icehaunter** [comment]
> All looks great 👍 
> 
> I note no tests. Presumably the existing tests exercise the code but might be nice to verify the intended dedupe behaviour.

@thruflo 
No tests because it's a bit late for me and I was hoping to deliver this for you today. We can merge + release now and I'll add tests tomorrow, or you can use local build of both Electric and Ts client until I add the tests tomorrow. Which do you prefer? I did manually test that it worked

**Comment by thruflo** [comment]
Yup, totally get it and appreciate your time and urgency. Merge+release and test when you have a moment would be great 👍

**Pull request merged**
