### PR TITLE
fix(electric): Deduplicate enum type definitions in the electrified schema

### LINKED ISSUE #893: error: value is already defined on enum
When an enum is declared and then used in more than one table, prisma seems to redeclare it's values multiple times.

In my project there are several tables using the same enum:
```sql
CREATE TYPE user_role AS enum(
  'manager',
  'editor',
  'reader'
);

CREATE TABLE project_users(
  project_user_id uuid PRIMARY KEY DEFAULT NULL, -- public.uuid_generate_v7(),
  account_id uuid DEFAULT NULL REFERENCES accounts(account_id) ON DELETE CASCADE ON UPDATE CASCADE,
  project_id uuid DEFAULT NULL REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id uuid DEFAULT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  role user_role DEFAULT NULL,
  label text DEFAULT NULL,
  deleted boolean DEFAULT NULL -- FALSE
);

CREATE TABLE subproject_users(
  subproject_user_id uuid PRIMARY KEY DEFAULT NULL, -- public.uuid_generate_v7(),
  account_id uuid DEFAULT NULL REFERENCES accounts(account_id) ON DELETE CASCADE ON UPDATE CASCADE,
  subproject_id uuid DEFAULT NULL REFERENCES subprojects(subproject_id) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id uuid DEFAULT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  role user_role DEFAULT NULL,
  label text DEFAULT NULL,
  deleted boolean DEFAULT NULL -- FALSE
);

CREATE TABLE place_users(
  place_user_id uuid PRIMARY KEY DEFAULT NULL, -- public.uuid_generate_v7(),
  account_id uuid DEFAULT NULL REFERENCES accounts(account_id) ON DELETE CASCADE ON UPDATE CASCADE,
  place_id uuid DEFAULT NULL REFERENCES places(place_id) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id uuid DEFAULT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  role user_role DEFAULT NULL,
  label text DEFAULT NULL,
  deleted boolean DEFAULT NULL -- FALSE
);
```

When generating the client, this error occurs:
```console
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Error: Command failed: node C:\Users\alexa\ps\node_modules\prisma\build\index.js generate --schema=".electric_migrations_tmp_O9QE4F\prisma\schema.prisma"
Error: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: Value "manager" is already defined on enum "user_role".
  -->  schema.prisma:995
   | 
994 |   reader
995 |   manager
996 |   editor
   | 
error: Value "editor" is already defined on enum "user_role".
  -->  schema.prisma:996
   | 
995 |   manager
996 |   editor
997 |   reader
   | 
error: Value "reader" is already defined on enum "user_role".
  -->  schema.prisma:997
   | 
996 |   editor
997 |   reader
998 |   manager
   | 
error: Value "manager" is already defined on enum "user_role".
  -->  schema.prisma:998
   | 
997 |   reader
998 |   manager
999 |   editor
   | 
error: Value "editor" is already defined on enum "user_role".
  -->  schema.prisma:999
   | 
998 |   manager
999 |   editor
1000 |   reader
   | 
error: Value "reader" is already defined on enum "user_role".
  -->  schema.prisma:1000
   | 
999 |   editor
1000 |   reader
1001 | }
   | 

Validation Error Count: 6
[Context: getDmmf]

Prisma CLI Version : 5.2.0

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:527:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node C:\\Users\\alexa\\ps\\node_modules\\prisma\\build\\index.js generate --schema=".electric_migrations_tmp_O9QE4F\\prisma\\schema.prisma"'
}
generate command failed: Generator script exited with error code: 1
```

Is this error in electric-sql or prisma?

### PR DESCRIPTION
**Pull request by alco**
Fixes #893.

### CODE REVIEW

**Review by magnetised — APPROVED** [review]
Super.

**Comment by KyleAMathews** [comment]
Is this released to the Docker instance? I'm still hitting the same error...

**Comment by alco** [comment]
@KyleAMathews which version are you on?

There's no automatic migration for this problem but it should get fixed for an existing electrified schema after you electrify a new table that has a column of an enum type. It can be the same enum type that had been electrified before.

**Comment by alco** [comment]
@KyleAMathews To answer your question, this change was included in version 0.9.3.

**Comment by KyleAMathews** [comment]
This is on the latest version with two tables being electrified with the same enum.

**Pull request merged**
