### PR TITLE
chore: Update table path param to be a query param

### PR DESCRIPTION
**Pull request by KyleAMathews**
Partially addresses https://github.com/electric-sql/electric/issues/1771

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Great thanks! I'll give this a through go over later & double-check docs, examples, etc. and then merge it in

**Comment by KyleAMathews** [comment]
Yeah `root_table` is useful in Elixir to be really clear about what table it is but since only one table is allowed in a shape request, just calling it "table" everywhere else is cleaner.

**Comment by KyleAMathews** [comment]
Ok, this is ready to go — all examples are tested & gave another look over docs.

Per https://github.com/electric-sql/electric/pull/1796#pullrequestreview-2388639969 we'll just either need to decide on the order of merging.

**Comment by KyleAMathews** [comment]
Not sure where those typescript errors are from — not reproducing locally.

**Comment by thruflo** [comment]
So everywhere we have table in the URL we need to switch to table as a param? Can you shout when this is merged so we can update parallel PRs like deployment docs and Elixir client.

**Comment by KyleAMathews** [comment]
The docs are already updated as part of this PR — we can just release it right away when we merge.

**Comment by icehaunter** [comment]
Superseded by #1900

**Pull request closed without merging**
