### PR TITLE
hotfix: make sure clients behave after server DB reset

### PR DESCRIPTION
**Pull request by icehaunter**

### CODE REVIEW

**Review by jamiegreen7 — COMMENTED** [review]
PHRASES

**Comment by icehaunter** [comment]
> PHRASES

I'm sorry @jamiegreen7, what's this about?

**Comment by jamiegreen7** [comment]
I need my phrase

**Comment by icehaunter** [comment]
> I need my phrase

@jamiegreen7, you seem confused, this is a repo for ElectricSQL tool, not anything to do with crypto or anything related to "phrases" at all

**Pull request merged**
