### PR TITLE
iff => if

### PR DESCRIPTION
**Pull request by KyleAMathews**
Noticed a typo and then found more of them!

### CODE REVIEW

**Comment by kevin-dp** [comment]
Hey @KyleAMathews, i don't think these are typos, but we really meant iff (if and only if).
Perhaps we have overdone it a bit and used it in too many places (i.e. in places where `if` would do equally well).

**Comment by KyleAMathews** [comment]
Ah .. ok, actually have never heard of that but I'll close.

**Comment by kevin-dp** [comment]
Hi @KyleAMathews, you are not the only one that doesn't know "iff".
It stems from my academic background where iff means <=> (logical equivalence) as compared to if which means => (logical implication). Let's indeed replace them by "if".

**Comment by thruflo** [comment]
This is me being a smart arse and using iff. I’d suggest let’s either simplify to “if” or expand to “if and only if”.

**Pull request merged**
