### PR TITLE
chore(docs): Update release notes

### PR DESCRIPTION
**Pull request by alco**
Preview: https://deploy-preview-129--electric-sql-website.netlify.app/docs/reference/release_notes#2024-05-02---v0102

### CODE REVIEW

**Comment by samwillis** [comment]
@msfstef I'm assuming that the dev toolbar isn't being released along side a release in the next day or so?

**Comment by msfstef** [comment]
@samwillis no don't think so, I'm currently reworking it so won't be done until next week

**Comment by samwillis** [comment]
@msfstef It's showing ups in the changelog for the main client: https://github.com/electric-sql/electric/pull/1161

**Comment by msfstef** [comment]
@samwillis yeah because I had to do some minor changes to expose a mock from the client so the patch touched the client - perhaps not necessary to include as a patch

**Comment by alco** [comment]
Sorry, I wasn't paying attention. I've removed all mentions of the debug toolbar from this PR.

**Review by samwillis — APPROVED** [review]

**Pull request merged**
