### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by aellerton**
- some typos

- some hyperlink fixes

- reduction of 'So', 'But' etc at start of sentences, while hopefully keeping the same light tone.

- "diagramme" - though I generally prefer international English spelling, in tech content I have come to see that the US spelling causes the least friction. For example, "colour" and "authorisation", which is how I would spell things personally, only add confusion vs "color" and "authorization". For that reason I changed "diagramme" to "diagram" for consistency.

- some readability tweaks because I was there :)

EDIT: if you'd prefer I reduce this change to only typos and hyperlink fixes, that's no problem :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey! Thanks for helping out. Yeah if you could remove the bigger edits that'd help. I'm the only American on the team so tread carefully haha on spelling cc @thruflo

**Comment by aellerton** [comment]
No problem!

Hah yeah I actually surprise myself changing things _into_ US spelling 😜

Cool, I'll come back to you soon...

**Comment by KyleAMathews** [comment]
Feel free to open a new PR @aellerton when you have a chance but I'm going to close this one now as it's fairly out of date.

**Comment by aellerton** [comment]
Thanks Kyle. Sorry, other commitments got in the way of coming back to
this.

**Pull request closed without merging**
