### PR TITLE
chore(docs): Add `ELECTRIC_FEATURES` environment variable to CLI

### PR DESCRIPTION
**Pull request by msfstef**
To be merged once https://github.com/electric-sql/electric/pull/1304 lands in main.

### CODE REVIEW

**Comment by samwillis** [comment]
@msfstef @magnetised is there a docs PR for the new `ELECTRIC_FEATURES` env var? These cli docs for the env var should link to the docs for the server env var and how it can be used.

**Comment by msfstef** [comment]
@samwillis you're right I don't see this in the docs anywhere but it is documented in code:
https://github.com/electric-sql/electric/blob/25523d96c0e73f3c80838b00d8b3764bed472615/components/electric/lib/electric/features.ex#L11-L18

**Comment by samwillis** [comment]
@msfstef Maybe this PR can add both parts of the docs?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and create this improvement!

**Pull request closed without merging**
