### PR TITLE
fix(client_cli): Proxy fixes 

### PR DESCRIPTION
**Pull request by davidmartos96**
A couple of minor issues I found:

1. ~~Use the prisma user in the db proxy url, otherwise non elecrified tables are generated.~~ Bad call, the prisma user is correctly being used for the introspection. The proxy url doesn't always need to use the prisma user. We can however log the correct proxy url used when generating the client, because the one in the config differs the one used for the introspection.
https://github.com/electric-sql/electric/blob/7fbf292ef1bcb07a71fd4e2a528d2cda965ac5ce/clients/typescript/src/cli/migrations/migrate.ts#L73
https://github.com/electric-sql/electric/blob/7fbf292ef1bcb07a71fd4e2a528d2cda965ac5ce/clients/typescript/src/cli/migrations/migrate.ts#L303-L309

2. Handle ssl mode when building the db url, so that when running locally, the db and proxy urls are built with `?sslmode=disable`. Some postgres migration clients won't connect without that flag in the url when running without ssl.

### CODE REVIEW

**Comment by samwillis** [comment]
Thanks @davidmartos96 for the changes, I've merged them into my branch of various fixes over here: https://github.com/electric-sql/electric/pull/834

I plan to finish this off, and do some more testing, tomorrow.

**Comment by alco** [comment]
@davidmartos96
> Some postgres migration clients won't connect without that flag in the url when running without ssl.

I'd like to know which clients have this.

**Comment by davidmartos96** [comment]
@alco `dbmate` is an example, where it's required to provide `?sslmode=disable` in the URL, and if I remember correctly, `go-migrate` too, which we used previously.

**Comment by alco** [comment]
> @alco `dbmate` is an example, where it's required to provide `?sslmode=disable` in the URL, and if I remember correctly, `go-migrate` too, which we used previously.

Thanks!

**Pull request merged**
