### PR TITLE
chore: add plausible to website

### PR DESCRIPTION
**Pull request by samwillis**

### CODE REVIEW

**Review by KyleAMathews — APPROVED** [review]
I assume it doesn't need any ids or auth?

**Comment by samwillis** [comment]
@KyleAMathews  nope, just this. It's the same, except for the `data-domain` as on pglite.dev.

**Comment by thruflo** [comment]
Note that plausible generally underreports traffic significantly and is 30-40% of the traffic reported on Netlify.

**Comment by KyleAMathews** [comment]
All js trackers do as so many people have blocker extensions installed.

Though also Netlify tends to overreport too as it i believe doesn't filter out bot traffic very well.

The best way to do analytics is to include the code in the first party js as then we only don't see data from people who block all js

**Pull request merged**
