### PR TITLE
chore: rename env variables so consitently prefixed with ELECTRIC_

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fix https://github.com/electric-sql/electric/issues/1927

### CODE REVIEW

**Comment by thruflo** [comment]
I think it would be useful to do this on top of the new deployment guide, given that has a new page documenting the env var config.

**Comment by KyleAMathews** [comment]
Is that going in right now too? This is another breaking change so I want it to go out with all the others (ideally today)

**Comment by KyleAMathews** [comment]
Happy to pr the updates separately to the doc page

**Comment by KyleAMathews** [comment]
ok merging and then I'll open a PR to the docs PR with the same updates

**Pull request merged**
